image:
  file: .gitpod.Dockerfile

tasks:
  - name: install eksctl
    command: |
      curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
      sudo mv /tmp/eksctl $HOME/bin
      
  - name: configure environment
    command: |
      export PATH="$HOME/bin:$PATH"
