# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Buld and deploy Documentation

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
    paths:
      - "docs/**"
      - "**/build-documentation.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "docs/**"
      - "**/build-documentation.yml"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Lint
        shell: bash
        run: |
          cd docs
          npm install 
          npm run docs:lint

      - name: Build site
        shell: bash
        run: |
          cd docs
          npm install 
          npm run docs:build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1.0.4
        with:
          path: docs/markdown/.vitepress/dist

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1.2.2

      - uses: actions/checkout@v3

      - name: Rebuild search index
        env:
          ALGOLIA_API_KEY: '${{ secrets.ALGOLIA_API_KEY }}'
          ALGOLIA_APP_ID: '${{ secrets.ALGOLIA_APPLICATION_ID }}'
        shell: bash
        run: |
          echo set
          docker run \
          -e "CONFIG=$(cat docs/algolia.config.json | jq -r tostring)" \
          -e "ALGOLIA_API_KEY=$ALGOLIA_API_KEY" \
          -e "ALGOLIA_APP_ID=$ALGOLIA_APP_ID" \
          algolia/docsearch-scraper:v1.16.0
