# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main", "feature/documentation_as_a_code"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
          bundler-cache: true
          cache-version: 1

      - uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ inputs.ruby-version }}-${{ inputs.cache-version }}
          restore-keys: |
              ${{ runner.os }}-gems-${{ inputs.ruby-version }}-${{ inputs.cache-version }}

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
          cache-dependency-path: docs/yarn.lock

      - name: Build site
        shell: bash
        run: |
          cd docs
          yarn install --immutable
          yarn docs:build

      - name: Rebuild search index
        env:
          ALGOLIA_API_KEY: '${{ secrets.ALGOLIA_API_KEY }}'
        shell: bash
        run: |
          # Bundle install
          bundle config path vendor/bundle
          cd docs/markdown/.vitepress/dist
          bundle install --jobs 4 --retry 3
          # Updating Algolia Index
          bundle exec jekyll algolia

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1.0.4
        with:
          path: docs/markdown/.vitepress/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1.2.2
